### ISSUE TITLE
[Linux]  puyovs.bin exec format error

### ISSUE THREAD

**Issue by SnivySquid65** [puyonexus/puyovs#50]
Hello!  I am having an issue with running Puyo Puyo Vs 2 on my Raspberry Pi.
Every time I open a terminal and run `./puyovs.bin` it does not work.  The terminal log looks something like this...
`myuser@raspi:~/Downloads/puyovs-b29-linux-x86/puyovs-linux-qt5-x86$ ./puyovs.bin`
`bash: ./puyovs.bin: cannot execute binary file: Exec format error`

My computer is a Raspberry Pi 4B, 8gb ram, running Ubuntu.
This computer has had history of rejecting 32 bit apps, no matter what I try.
Any solutions?

**Comment by jchv** [comment]
The issue here is CPU architecture.

A Raspberry Pi is an ARM-based device. Specifically, the Pi 4B contains a Broadcom BCM2711 CPU, which contains Cortex-A72 CPU cores. Those Cortex-A72 cores can be used with a 32-bit ARMv7-A AArch32 ("ARM32") operating system, or a 64-bit ARMv8 AArch64 ("ARM64") operating system.

When you say "32-bit" or "64-bit", nominally it refers to the word size of the processor's instruction set architecture. However, not all "32-bit" architectures are the same. As you can see by that filename, `puyovs-b29-linux-x86`, the PuyoVS binaries are compiled for Intel x86 32-bit architecture, not ARM32. The Intel x86 and Intel x86-64/AMD64 architectures are completely different from and not compatible with ARM32 and ARM64.

As of now, PuyoVS has not been ported to run on a Raspberry Pi or ARM Linux. It is certainly something that should be tackled in the future, but up until recently there were even more complexities than just CPU architecture, as up until relatively recently most ARM computers only offered limited GPU driver support. Now that Raspberry Pi computers offer desktop OpenGL inside of normal windowing systems, a Puyo VS port is much more doable.

So what do you do for now? Unfortunately, I am not really sure what the best way to go is. If you just want to run the latest version of PuyoVS on a Raspberry Pi, you might be best off seeing if you can get emulation software like [Hangover](https://github.com/AndreRH/hangover/releases/tag/hangover-9.0) working. Theoretically, Hangover could just run the Windows version of PuyoVS, possibly. Failing that, you can set up Box86, which can either be used to run x86 Linux PuyoVS, or x86 Linux Wine + Windows x86 PuyoVS. However, I don't know how well it will work.

**Comment by SnivySquid65** [comment]
Thanks!  I'll try the emulators you mentioned.

**Comment by SnivySquid65** [comment]
Couldn't set up Box86, tried Manjaro, also didn't work.  Wine just got removed too...
Gonna mark as unresolved.

**Comment by SnivySquid65** [comment]
Thanks for trying to help though, @jchv!
